name: Deploy Byte Bank

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Connect and deploy to EC2
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm
                      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
                      cd ${{ secrets.BYTE_BANK_APP }} 
                      git pull origin master 
                      /home/${{secrets.EC2_USER}}/.nvm/versions/node/v22.19.0/bin/npm install 
                      /home/${{secrets.EC2_USER}}/.nvm/versions/node/v22.19.0/bin/npm run build 
                      /home/${{secrets.EC2_USER}}/.nvm/versions/node/v22.19.0/bin/pm2 start byte-bank --update-env 
                      /home/${{secrets.EC2_USER}}/.nvm/versions/node/v22.19.0/bin/pm2 save 
                      echo "âœ… Deployment successful."
